### ISSUE TITLE
bitbucket support?

### ISSUE THREAD

**Issue by jjn2009** [aircover/aircover#4]
any timeline for this?

**Comment by bradrydzewski** [comment]
This isn't something I have the bandwidth to implement at the moment, however, I've committed to making the source code available by end of April and will absolutely accept pull requests.

**Comment by jjn2009** [comment]
awesome, thats what I figured.

**Comment by kirillDanshin** [comment]
@bradrydzewski hi! as you said the source code should be available by end of April. today is July 20th. did you mean end of April in 2017? or maybe any news?
